language: python
dist: xenial
sudo: required
env:
python:
    - "3.5"
    - "3.6"
    - "3.7-dev"
install:
    - "pip install -Ur requirements.txt"
    - "pip install ."
script:
    - "make test"
matrix:
    allow_failures:
        - python: "3.7-dev"

    include:
        - name: "black linting"
          python: "3.6"
          env: LINTING=true
          install:
            - "pip install black"
          script:
              - "make lint"
